USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE ROLE DE_BI COMMENT =  'THIS IS FOR DATA ENGINEER';
CREATE OR REPLACE ROLE DOCTOR COMMENT =  'THIS IS FOR DOCTOR';
GRANT ROLE DE_BI TO ROLE SYSADMIN;
GRANT ROLE DOCTOR TO ROLE SYSADMIN;


-- SET UP ROLE FOR DATA ENGINEER
GRANT USAGE ON WAREHOUSE QOOBEE_WH TO ROLE DE_BI;
GRANT USAGE ON DATABASE FVHIS_DE TO ROLE DE_BI;
GRANT USAGE ON SCHEMA "DISEASE_DIAGNOSIS" TO ROLE DE_BI;
GRANT SELECT ON ALL TABLES IN DATABASE FVHIS_DE TO ROLE DE_BI;


-- SET UP ROLE FOR DOCTOR
GRANT USAGE ON WAREHOUSE QOOBEE_WH TO ROLE DOCTOR;
GRANT USAGE ON DATABASE FVHIS_DOC TO ROLE DOCTOR;
GRANT USAGE ON SCHEMA "DISEASE_DIAGNOSIS_UPTODATE" TO ROLE DOCTOR;
GRANT SELECT ON ALL TABLES IN DATABASE FVHIS_DE TO ROLE DOCTOR;

CREATE OR REPLACE USER DATAENGINEER01
    PASSWORD = 'Hayvuilendi123'
    DISPLAY_NAME = 'DATAENGINEER01 USER'
    DEFAULT_ROLE = DE_BI
    DEFAULT_WAREHOUSE = BEEON_WH;

-- GRANT ROLE FOR ANY USER    
GRANT ROLE SYSADMIN TO USER HUNGNG;


-- CHANGE THE OWNER SHIP TABLE
GRANT OWNERSHIP ON TABLE "MANUWORKS2021"."SALES"."FACT_SALES" TO ROLE SYSADMIN;