-- Create roles and Grant permissions
-- Create USERS
CREATE USER longbv
PASSWORD = 'password123' 
DEFAULT_ROLE = "TRAINER";

CREATE USER mainq
PASSWORD = 'password123' 
DEFAULT_ROLE = "TRAINER";

--create roles trainer and grant access
CREATE OR REPLACE ROLE TRAINER;
GRANT ROLE TRAINER TO ROLE SYSADMIN;

GRANT ROLE TRAINER TO USER longbv;
GRANT ROLE TRAINER TO USER mainq;

GRANT USAGE, MONITOR ON DATABASE PIPELINE_GROUP02 TO ROLE TRAINER;
GRANT USAGE, MONITOR ON SCHEMA DATAWAREHOUSE_DIAGNOSIS TO ROLE TRAINER;

GRANT SELECT ON ALL TABLES IN SCHEMA DATAWAREHOUSE_DIAGNOSIS TO ROLE TRAINER;
GRANT MONITOR, OPERATE, USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRAINER;